name = input()
number = int(input())
ch = int(input())
cs = int(input())
pd = int(input())
print('Name:{}'.format(name))
print('ID:{}'.format(number))
print('Average:{}'.format((ch+cs+pd)//3))
print('Total::{}'.format(ch+cs+pd))